manifest:
#  defaults:
#   revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: hisa222
      url-base: https://github.com/hisa222
      
    - name: prospector
      url-base: https://github.com/t-ogura
      
    - name: ShiniNet
      url-base: https://github.com/ShiniNet
      
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      # remote: zmkfirmware
      remote: hisa222
      revision: main
      import: app/west.yml
      
    - name: zmk-pmw3610-driver
      remote: hisa222
      revision: main
      
    - name: prospector-zmk-module
      remote: prospector
      revision: v1.0.0
      path: modules/prospector-zmk-module

      # https://github.com/ShiniNet/cirque-input-module
    - name: cirque-input-module
      remote: ShiniNet
      revision: main
      path: modules/cirque-input-module-shininet

      # https://github.com/badjeff/zmk-analog-input-driver
    - name: zmk-analog-input-driver
      remote: badjeff
      revision: main
  self:
    path: config
